language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
install:
  - pip install . --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - pip install coveralls
script:
  coverage run --source=datatables setup.py test
after_success:
  coveralls
