sudo: false

language: python

python:
  - "3.6"

install:
  - make install
  - make lint

script: make test-ci

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    branch: master
    tags: true